// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMatricula.mvc.Database;

#nullable disable

namespace SistemaMatricula.mvc.Migrations
{
    [DbContext(typeof(MatriculaContext))]
    partial class MatriculaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaMatricula.mvc.Models.Aluno", b =>
                {
                    b.Property<int>("MatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatriculaId"), 1L, 1);

                    b.Property<string>("Curso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("CAMPO-VAZIO")
                        .HasColumnName("NOME_CURSO");

                    b.Property<DateTime>("DataMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(959))
                        .HasColumnName("DATA_MATRICULA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("CAMPO-VAZIO")
                        .HasColumnName("NOME_ALUNO");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CAMPO-VAZIO")
                        .HasColumnName("UNIDADE");

                    b.HasKey("MatriculaId");

                    b.HasIndex("MatriculaId")
                        .HasDatabaseName("IX_MATRICULA_UNIQUE");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_NOME_UNIQUE");

                    b.ToTable("TB_MATRICULAS", (string)null);

                    b.HasData(
                        new
                        {
                            MatriculaId = 1,
                            Curso = "Análise e Desenvolvimento de Sistemas",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1041),
                            Nome = "Erik Fernandes",
                            Unidade = "Vergueiro"
                        },
                        new
                        {
                            MatriculaId = 2,
                            Curso = "Enfermagem",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1043),
                            Nome = "Marcos Felipe",
                            Unidade = "São Judas"
                        },
                        new
                        {
                            MatriculaId = 3,
                            Curso = "Odontólogia",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1044),
                            Nome = "Mariana Dias",
                            Unidade = "Vila Mariana"
                        },
                        new
                        {
                            MatriculaId = 4,
                            Curso = "Publicidade e Propaganda",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1045),
                            Nome = "Leticia Silva",
                            Unidade = "Paulista"
                        },
                        new
                        {
                            MatriculaId = 5,
                            Curso = "Culínaria",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1046),
                            Nome = "Beatriz Reis",
                            Unidade = "Praça da Arvoré"
                        },
                        new
                        {
                            MatriculaId = 6,
                            Curso = "Administração",
                            DataMatricula = new DateTime(2023, 7, 24, 13, 47, 10, 345, DateTimeKind.Local).AddTicks(1047),
                            Nome = "Vinicius Muller",
                            Unidade = "Saúde"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
